package com.llmocr.mcp.invoice.domain;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * MetadataKeyDefinition Entity
 * 
 * Defines allowed metadata keys and their descriptions.
 * Similar to LineItemCategoryRule, this controls which metadata keys are valid
 * and provides documentation for each key.
 * 
 * Examples:
 * - generated_kwh: "Total kWh generated by the solar system"
 * - contracted_rate: "Negotiated rate per kWh"
 * - meter_number: "Unique meter identifier"
 */
@Entity
@Table(name = "metadata_key_definition", schema = "mcp_invoice",
       uniqueConstraints = @UniqueConstraint(columnNames = {"tenant_id", "key_code"}))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class MetadataKeyDefinition {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "key_code", nullable = false, length = 255)
    private String keyCode;

    @Column(name = "display_name", nullable = false, length = 255)
    private String displayName;

    @Column(name = "description", columnDefinition = "TEXT", nullable = false)
    private String description;

    @Column(name = "category", length = 100)
    private String category; // e.g., "GENERATION", "RATES", "IDENTIFIERS", "BILLING", "PERFORMANCE", "CREDITS", "CUSTOM"

    @Column(name = "data_type", length = 50)
    private String dataType; // e.g., "STRING", "NUMBER", "DECIMAL", "PERCENTAGE", "DATE"

    @Column(name = "example_value", length = 500)
    private String exampleValue;

    @Column(name = "required", columnDefinition = "BOOLEAN DEFAULT FALSE")
    private Boolean required;

    @Column(name = "billable", columnDefinition = "BOOLEAN DEFAULT FALSE")
    private Boolean billable; // Whether this metadata affects billing

    @Column(name = "active", columnDefinition = "BOOLEAN DEFAULT TRUE")
    private Boolean active; // Allow disabling keys without deleting them

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "created_by", length = 100)
    private String createdBy;

    @Column(name = "updated_by", length = 100)
    private String updatedBy;
}
