package com.llmocr.mcp.invoice.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.*;
import java.util.List;

/**
 * Request DTO for bulk line item operations
 * 
 * Supports adding up to 1000 line items in a single MCP call,
 * dramatically improving performance for batch operations.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonIgnoreProperties(ignoreUnknown = true)
public class BulkLineItemRequest {

    /**
     * The invoice ID to which line items will be added
     */
    private Long invoiceId;

    /**
     * List of line items to add (up to 1000)
     */
    private List<LineItemInput> lineItems;

    /**
     * Inner class representing a line item input
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class LineItemInput {
        /**
         * Line number - DEPRECATED: Now auto-generated by the backend.
         * If provided, it will be IGNORED. Sequential line numbers (10, 20, 30...)
         * are automatically assigned based on existing line items in the invoice.
         */
        @Deprecated
        @com.fasterxml.jackson.annotation.JsonProperty(required = false)
        private Integer lineNumber;

        /**
         * Description of the line item (REQUIRED)
         */
        @com.fasterxml.jackson.annotation.JsonProperty(required = true)
        private String description;

        /**
         * Quantity as a string (e.g., "10.50", "1", etc.) - OPTIONAL
         */
        @com.fasterxml.jackson.annotation.JsonProperty(required = false)
        private String quantity;

        /**
         * Unit price as a string (e.g., "$45.00", "45.00", etc.) - OPTIONAL
         */
        @com.fasterxml.jackson.annotation.JsonProperty(required = false)
        private String unitPrice;

        /**
         * Total amount for the line (e.g., "450.00", "$450", "(450.00)" for negative, etc.)
         * Supports currency symbols and various formats
         * This is the line total - matches the database field line_total (REQUIRED)
         */
        @com.fasterxml.jackson.annotation.JsonProperty(required = true)
        private String lineTotal;

        /**
         * Unit of measure (e.g., "kWh", "units", "gallons", etc.) - OPTIONAL
         */
        @com.fasterxml.jackson.annotation.JsonProperty(required = false)
        private String unitOfMeasure;

        /**
         * Category code (REQUIRED). Must be valid for tenant.
         * Call getAvailableCategories() first to get valid category codes.
         */
        @com.fasterxml.jackson.annotation.JsonProperty(required = true)
        private String category;
    }
}
