import { ContractReviewData } from '../types/contractReview';

/**
 * Mock contract review data for energy sector POC
 * This data will be used for invoice variance assessment
 */
export const mockContractReviews: ContractReviewData[] = [
  {
    id: 1,
    metadata: {
      contractName: 'Desert Solar Project - Power Purchase Agreement',
      fundName: 'ACME RENEWABLES USA LLC',
      projectName: 'Desert Solar Project (Maricopa County, Arizona)',
      contractType: 'Power Purchase Agreement (PPA)',
      codDate: '03/31/2025',
      technologies: ['PV', 'BESS']
    },
    summary: {
      totalObligationsExtracted: 36,
      totalMissingObligations: 8,
      totalRisksUnclear: 12,
      selfCheckQuestion: 'Have any obligations been missed?',
      selfCheckAnswer: 'Yes',
      selfCheckExplanation: 'Multiple critical obligations are missing including Force Majeure definition, Indemnification clause, and Limitation of Liability.'
    },
    extraction: {
      preCodObligations: [
        {
          ppaId: 'E001',
          clauseReference: 'Section 2.1(a)',
          obligationCategory: 'Deliverable',
          obligationDescription: 'Provide Notice to Proceed when financial close achieved',
          obligationSummary: 'Seller must notify Buyer in writing when financial close is achieved, no later than April 30, 2024',
          clauseText: 'Seller shall provide written notice to Buyer when financial close is achieved, no later than April 30, 2024.',
          task: 'Provide Notice to Proceed when financial close achieved',
          responsibleParty: 'Seller',
          counterparty: 'Buyer',
          contractDate: '01/15/2024',
          firstTaskDueDate: '04/30/2024',
          obligationFrequency: 'One-time'
        },
        {
          ppaId: 'E002',
          clauseReference: 'Section 2.1(b)',
          obligationCategory: 'Documentation',
          obligationDescription: 'Deliver evidence of site control (lease or ownership)',
          obligationSummary: 'Seller must deliver evidence of site control to Buyer within 30 days of Effective Date',
          clauseText: 'Seller shall deliver evidence of site control (lease or ownership) to Buyer within thirty (30) days of the Effective Date.',
          task: 'Deliver evidence of site control',
          responsibleParty: 'Seller',
          counterparty: 'Buyer',
          firstTaskDueDate: '02/14/2024',
          obligationFrequency: 'One-time'
        }
      ],
      postCodObligations: [
        {
          ppaId: 'E015',
          clauseReference: 'Section 4.1',
          obligationCategory: 'Deliverable',
          obligationDescription: 'Sell and deliver 100% of Energy and Environmental Attributes',
          obligationSummary: 'Seller shall sell and deliver 100% of Energy generated by Project during Term',
          clauseText: 'Seller shall sell and deliver to Buyer, and Buyer shall purchase and receive from Seller, one hundred percent (100%) of the Energy and Environmental Attributes generated by the Project during the Term.',
          task: 'Sell and deliver 100% of Energy',
          responsibleParty: 'Seller',
          counterparty: 'Buyer',
          obligationFrequency: 'Other'
        },
        {
          ppaId: 'E017',
          clauseReference: 'Section 5.2',
          obligationCategory: 'Reporting',
          obligationDescription: 'Provide monthly statement detailing all Energy generated',
          obligationSummary: 'Seller shall provide monthly statement within 5 Business Days after end of each month',
          clauseText: 'Seller shall provide Buyer with a monthly statement detailing all Energy generated during the preceding calendar month within five (5) Business Days after the end of each month.',
          task: 'Submit monthly energy generation report',
          responsibleParty: 'Seller',
          counterparty: 'Buyer',
          obligationFrequency: 'Monthly'
        }
      ]
    },
    assumptionsLog: [
      {
        logId: 'A001',
        trigger: 'Prudent Electrical Practices - undefined term',
        proposedAssumption: 'Assumed to mean industry-standard O&M practices per IEEE/NERC standards',
        status: 'Pending Review'
      },
      {
        logId: 'A002',
        trigger: 'Force Majeure Events - referenced but not defined',
        proposedAssumption: 'Assumed standard force majeure definition applies (acts of God, war, etc.)',
        status: 'Pending Review'
      }
    ],
    obligationsNotFound: [
      {
        ppaId: 'M001',
        missingObligation: 'Force Majeure Definition & Procedures',
        reference: 'Article 6.2 (referenced but not defined)',
        severity: 'High'
      },
      {
        ppaId: 'M002',
        missingObligation: 'Indemnification Clause',
        reference: 'Not present in Article 15',
        severity: 'High'
      },
      {
        ppaId: 'M003',
        missingObligation: 'Limitation of Liability',
        reference: 'Not present in Article 15',
        severity: 'High'
      }
    ],
    risksUnclear: [
      {
        ppaId: 'R001',
        textExcerpt: 'Prudent Electrical Practices (Section 8.1)',
        issueType: 'Vague',
        comment: 'Undefined term. No reference to IEEE, NERC, or other standards.'
      },
      {
        ppaId: 'R002',
        textExcerpt: 'Environmental Attributes (Section 4.1)',
        issueType: 'Wording Risk',
        comment: 'Undefined term. Unclear if includes RECs, carbon credits, or other attributes.'
      }
    ],
    rateSchedules: [
      {
        scheduleName: 'Standard PPA Rates - Desert Solar',
        accountNumbers: ['APS-12345', 'APS-67890'],
        rates: [
          {
            rateId: 'R001',
            rateType: 'Energy',
            description: 'Energy Charge - Solar PV',
            unitPrice: 0.0450,
            unitOfMeasure: 'kWh',
            effectiveDate: '03/31/2025',
            expirationDate: '03/31/2045',
            clauseReference: 'Schedule A, Section 1.1',
            notes: 'Fixed rate for 20-year term'
          },
          {
            rateId: 'R002',
            rateType: 'Energy',
            description: 'Energy Charge - BESS Discharge',
            unitPrice: 0.0520,
            unitOfMeasure: 'kWh',
            effectiveDate: '03/31/2025',
            expirationDate: '03/31/2045',
            clauseReference: 'Schedule A, Section 1.2',
            notes: 'Premium rate for battery storage discharge'
          },
          {
            rateId: 'R003',
            rateType: 'Demand',
            description: 'Capacity Payment',
            unitPrice: 8.50,
            unitOfMeasure: 'kW',
            effectiveDate: '03/31/2025',
            expirationDate: '03/31/2045',
            clauseReference: 'Schedule A, Section 2.1',
            notes: 'Per kW-month capacity payment'
          },
          {
            rateId: 'R004',
            rateType: 'Fixed',
            description: 'Monthly Service Charge',
            unitPrice: 250.00,
            unitOfMeasure: 'Fixed',
            effectiveDate: '03/31/2025',
            expirationDate: '03/31/2045',
            clauseReference: 'Schedule B',
            notes: 'Fixed monthly fee'
          }
        ]
      }
    ],
    createdAt: '2024-12-04T10:30:00Z',
    processedBy: 'Claude 3.5 Sonnet',
    pdfUrl: '/api/contracts/1/pdf'
  },
  {
    id: 2,
    metadata: {
      contractName: 'Wind Valley Project - Power Purchase Agreement',
      fundName: 'ACME RENEWABLES USA LLC',
      projectName: 'Wind Valley Wind Farm (Texas)',
      contractType: 'Power Purchase Agreement (PPA)',
      codDate: '06/15/2025',
      technologies: ['Wind']
    },
    summary: {
      totalObligationsExtracted: 42,
      totalMissingObligations: 3,
      totalRisksUnclear: 5,
      selfCheckQuestion: 'Have any obligations been missed?',
      selfCheckAnswer: 'No',
      selfCheckExplanation: 'All clauses containing obligation keywords have been reviewed and extracted.'
    },
    extraction: {
      preCodObligations: [
        {
          ppaId: 'E001',
          clauseReference: 'Section 3.1',
          obligationCategory: 'Documentation',
          obligationDescription: 'Submit Interconnection Agreement',
          obligationSummary: 'Seller must submit executed IA to Buyer 60 days prior to COD',
          clauseText: 'Seller shall submit to Buyer a fully executed Interconnection Agreement no later than sixty (60) days prior to the Scheduled COD.',
          task: 'Submit executed Interconnection Agreement',
          responsibleParty: 'Seller',
          counterparty: 'Buyer',
          firstTaskDueDate: '04/16/2025',
          obligationFrequency: 'One-time'
        }
      ],
      postCodObligations: [
        {
          ppaId: 'E020',
          clauseReference: 'Section 6.1',
          obligationCategory: 'Reporting',
          obligationDescription: 'Quarterly production reports',
          obligationSummary: 'Seller must provide quarterly generation reports to Buyer',
          clauseText: 'Seller shall provide Buyer with quarterly reports detailing all Energy generated within ten (10) Business Days after the end of each quarter.',
          task: 'Submit quarterly production report',
          responsibleParty: 'Seller',
          counterparty: 'Buyer',
          obligationFrequency: 'Quarterly'
        }
      ]
    },
    assumptionsLog: [
      {
        logId: 'A001',
        trigger: 'Business Day - not defined in contract',
        proposedAssumption: 'Assuming Business Day means Monday-Friday excluding federal holidays',
        status: 'Approved'
      }
    ],
    obligationsNotFound: [
      {
        ppaId: 'M001',
        missingObligation: 'Confidentiality Clause',
        reference: 'Standard PPA Section 14',
        severity: 'Medium'
      }
    ],
    risksUnclear: [
      {
        ppaId: 'R001',
        textExcerpt: 'Commercially reasonable efforts',
        issueType: 'Vague',
        comment: 'Standard not defined in contract'
      }
    ],
    rateSchedules: [
      {
        scheduleName: 'Wind PPA Rates',
        accountNumbers: ['ERCOT-54321'],
        rates: [
          {
            rateId: 'R001',
            rateType: 'Energy',
            description: 'Wind Energy - Peak Hours',
            unitPrice: 0.0380,
            unitOfMeasure: 'kWh',
            effectiveDate: '06/15/2025',
            timeOfUse: 'Peak (6AM-10PM)',
            clauseReference: 'Exhibit A',
            notes: 'Higher rate during peak demand'
          },
          {
            rateId: 'R002',
            rateType: 'Energy',
            description: 'Wind Energy - Off-Peak Hours',
            unitPrice: 0.0280,
            unitOfMeasure: 'kWh',
            effectiveDate: '06/15/2025',
            timeOfUse: 'Off-Peak (10PM-6AM)',
            clauseReference: 'Exhibit A',
            notes: 'Reduced rate during off-peak'
          }
        ]
      }
    ],
    createdAt: '2024-12-03T15:45:00Z',
    processedBy: 'GPT-4o',
    pdfUrl: '/api/contracts/2/pdf'
  },
  {
    id: 3,
    metadata: {
      contractName: 'Coastal Solar Farm - Service Agreement',
      fundName: 'ACME RENEWABLES FUND II',
      projectName: 'Coastal Solar Farm (North Carolina)',
      contractType: 'Operations & Maintenance Agreement',
      codDate: '01/01/2025',
      technologies: ['PV']
    },
    summary: {
      totalObligationsExtracted: 28,
      totalMissingObligations: 2,
      totalRisksUnclear: 8,
      selfCheckQuestion: 'Have any obligations been missed?',
      selfCheckAnswer: 'No',
      selfCheckExplanation: 'Contract is well-defined with minimal ambiguity.'
    },
    extraction: {
      preCodObligations: [],
      postCodObligations: [
        {
          ppaId: 'E001',
          clauseReference: 'Section 2.1',
          obligationCategory: 'Maintenance',
          obligationDescription: 'Perform preventive maintenance',
          obligationSummary: 'Service Provider shall perform preventive maintenance per schedule',
          clauseText: 'Service Provider shall perform preventive maintenance on all Project equipment in accordance with manufacturer recommendations and industry best practices.',
          task: 'Execute preventive maintenance program',
          responsibleParty: 'Service Provider',
          counterparty: 'Owner',
          obligationFrequency: 'Monthly'
        }
      ]
    },
    assumptionsLog: [],
    obligationsNotFound: [
      {
        ppaId: 'M001',
        missingObligation: 'Insurance Requirements',
        reference: 'Standard O&M Section 7',
        severity: 'Low'
      }
    ],
    risksUnclear: [
      {
        ppaId: 'R001',
        textExcerpt: 'Industry best practices',
        issueType: 'Vague',
        comment: 'No specific standards referenced (IEEE, NFPA, etc.)'
      }
    ],
    rateSchedules: [
      {
        scheduleName: 'O&M Service Rates',
        rates: [
          {
            rateId: 'R001',
            rateType: 'Fixed',
            description: 'Monthly O&M Base Fee',
            unitPrice: 15000.00,
            unitOfMeasure: 'Fixed',
            effectiveDate: '01/01/2025',
            clauseReference: 'Schedule 1',
            notes: 'Includes routine maintenance'
          },
          {
            rateId: 'R002',
            rateType: 'Other',
            description: 'Emergency Callout Rate',
            unitPrice: 250.00,
            unitOfMeasure: 'Other',
            effectiveDate: '01/01/2025',
            clauseReference: 'Schedule 2',
            notes: 'Per hour for emergency repairs'
          }
        ]
      }
    ],
    createdAt: '2024-12-02T09:15:00Z',
    processedBy: 'Claude 3.5 Sonnet',
    pdfUrl: '/api/contracts/3/pdf'
  }
];

